language: java
jdk:
  - oraclejdk8  
deploy:
  provider: heroku
  api_key:
    secure: "ee0a7370-66fa-424d-adfe-aef14d13cd56"
  app: software-structures
  strategy: git
after_deploy: "./mvnw spring-boot:run"

