language: java
deploy:
  provider: heroku
  api_key:
    secure: "010f71d5-4637-492a-8c99-56ee7d69b002"
  app: software-structures
  run: "mvn spring-boot:run"
  jdk:
    - oraclejdk8
  strategy: git

