language: java
jdk:
  - oraclejdk8  
deploy:
  provider: heroku
  api_key:
    secure: "0eaae3d8-12f1-40cb-9403-6d72502a4e4d"
  app: software-structures
  strategy: git
after_deploy: "./mvnw spring-boot:run"

